# Generated by Django 5.1.5 on 2025-02-03 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('knowledge_level', models.CharField(max_length=20)),
                ('short_term_fluctuations', models.CharField(max_length=50)),
                ('risk_appetite', models.CharField(max_length=20)),
                ('investment_horizon', models.CharField(max_length=20)),
                ('financial_goal', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocks', models.FloatField()),
                ('fd', models.FloatField()),
                ('sips', models.FloatField()),
                ('commodities', models.FloatField()),
                ('bonds', models.FloatField()),
                ('cash', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.userprofile')),
            ],
        ),
    ]
