# Generated by Django 5.1.5 on 2025-02-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='investment_horizon',
            field=models.CharField(max_length=30),
        ),
    ]
