# Generated by Django 5.1.5 on 2025-02-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_userprofile_investment_horizon'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='financial_goal',
            field=models.CharField(default='Stability', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='investment_horizon',
            field=models.CharField(default='Short-term (1-5 years)', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='knowledge_level',
            field=models.CharField(default='Beginner', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='risk_appetite',
            field=models.CharField(default='Low', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='short_term_fluctuations',
            field=models.CharField(default='Short-term (1-5 years)', max_length=30),
            preserve_default=False,
        ),
    ]
